import { AppDataSource } from './data-source';
import { RecipeData } from './interface/recipe.interface';
import { Recipe } from './recipes/recipe.entity';

const seedDatabase = async () => {
  try {
    console.log('Seeding database...');

    await AppDataSource.initialize();

    const recipeRepository = AppDataSource.getRepository(Recipe);

    const recipes: RecipeData[] = [
      {
        title: 'Spaghetti Carbonara',
        description:
          'Classic Italian pasta with eggs, cheese, pancetta, and pepper.',
        ingredients: [
          '400g spaghetti',
          '4 large eggs',
          '200g pancetta',
          '100g Pecorino Romano cheese',
          '100g Parmigiano Reggiano',
          'Black pepper',
          'Salt',
        ],
        instructions: [
          'Bring a large pot of salted water to boil and cook spaghetti until al dente.',
          'While pasta cooks, fry pancetta until crispy.',
          'In a bowl, whisk eggs and grated cheese together.',
          'Combine hot pasta with egg mixture and pancetta, stirring quickly to create a creamy sauce.',
          'Season with black pepper and serve immediately.',
        ],
        category: 'Main Course',
        isVegetarian: false,
        isGlutenFree: false,
        containsEgg: true,
        region: 'Italy',
        prepTime: '10 minutes',
        cookTime: '20 minutes',
        servings: 4,
        difficulty: 'Medium',
        calories: 650,
        protein: 25,
        carbs: 65,
        fat: 35,
        notes: 'Best served immediately while hot',
      },
      {
        title: 'American Pancakes',
        description:
          'Fluffy, golden pancakes served with maple syrup and butter.',
        ingredients: [
          '2 cups all-purpose flour',
          '2 large eggs',
          '1½ cups milk',
          '2 tsp baking powder',
          '3 tbsp sugar',
          '½ tsp salt',
          '3 tbsp melted butter',
          'Maple syrup for serving',
        ],
        instructions: [
          'Mix flour, sugar, baking powder, and salt in a bowl.',
          'In another bowl, whisk eggs, milk, and melted butter.',
          'Combine wet and dry ingredients until just mixed.',
          'Heat a non-stick pan over medium heat.',
          'Pour ¼ cup batter for each pancake.',
          'Cook until bubbles form, then flip and cook the other side.',
        ],
        category: 'Breakfast',
        isVegetarian: true,
        isGlutenFree: false,
        containsEgg: true,
        region: 'USA',
        prepTime: '10 minutes',
        cookTime: '20 minutes',
        servings: 4,
        difficulty: 'Easy',
        calories: 280,
        protein: 8,
        carbs: 42,
        fat: 9,
        notes:
          'Let batter rest for 5 minutes before cooking for fluffier pancakes',
      },
      {
        title: 'Tomato Basil Soup',
        description:
          'A classic, comforting soup made with ripe tomatoes and fresh basil.',
        ingredients: [
          '8 ripe tomatoes, chopped',
          '1 cup fresh basil leaves',
          '4 cloves garlic, minced',
          '1 large onion, diced',
          '3 tbsp olive oil',
          '4 cups vegetable broth',
          'Salt and pepper to taste',
          '½ cup heavy cream (optional)',
        ],
        instructions: [
          'Heat olive oil in a large pot over medium heat.',
          'Sauté onion and garlic until softened.',
          'Add tomatoes and cook for 10 minutes.',
          'Add broth and simmer for 20 minutes.',
          'Blend soup until smooth.',
          'Stir in basil and cream if using.',
        ],
        category: 'Soup',
        isVegetarian: true,
        isGlutenFree: true,
        containsEgg: false,
        region: 'Italy',
        prepTime: '15 minutes',
        cookTime: '35 minutes',
        servings: 6,
        difficulty: 'Easy',
        calories: 150,
        protein: 3,
        carbs: 12,
        fat: 11,
        notes: 'Can be served hot or chilled',
      },
      {
        title: 'Classic Caesar Salad',
        description:
          'Crisp romaine lettuce with traditional Caesar dressing, garlic croutons, and parmesan.',
        ingredients: [
          '2 heads romaine lettuce',
          '1 cup Caesar dressing',
          '1 cup garlic croutons',
          '½ cup parmesan cheese, freshly grated',
          '2 anchovy fillets (optional)',
          'Fresh black pepper',
        ],
        instructions: [
          'Wash and chop romaine lettuce into bite-sized pieces.',
          'Toss lettuce with Caesar dressing.',
          'Add croutons and most of the parmesan.',
          'Top with remaining cheese and fresh pepper.',
        ],
        category: 'Salad',
        isVegetarian: false,
        isGlutenFree: false,
        containsEgg: true,
        region: 'USA',
        prepTime: '15 minutes',
        cookTime: '0 minutes',
        servings: 4,
        difficulty: 'Easy',
        calories: 320,
        protein: 8,
        carbs: 12,
        fat: 28,
        notes: 'Traditional dressing contains raw egg yolk and anchovies',
      },
      {
        title: 'Beef Tacos',
        description:
          'Mexican-style tacos with seasoned ground beef and fresh toppings.',
        ingredients: [
          '1 lb ground beef',
          '1 packet taco seasoning',
          '12 corn tortillas',
          'Lettuce, shredded',
          'Tomatoes, diced',
          'Cheddar cheese, shredded',
          'Sour cream',
          'Hot sauce',
        ],
        instructions: [
          'Brown ground beef in a large skillet.',
          'Add taco seasoning and water, simmer until thickened.',
          'Warm tortillas in a separate pan.',
          'Assemble tacos with meat and toppings.',
        ],
        category: 'Main Course',
        isVegetarian: false,
        isGlutenFree: true,
        containsEgg: false,
        region: 'Mexico',
        prepTime: '15 minutes',
        cookTime: '20 minutes',
        servings: 4,
        difficulty: 'Easy',
        calories: 380,
        protein: 23,
        carbs: 25,
        fat: 22,
        notes: 'Corn tortillas are traditional and gluten-free',
      },
      {
        title: 'Vegetable Curry',
        description:
          'A flavorful curry with mixed vegetables in a rich coconut sauce.',
        ingredients: [
          '2 carrots, chopped',
          '2 potatoes, cubed',
          '1 cauliflower, florets',
          '1 can coconut milk',
          '2 tbsp curry powder',
          '1 onion, diced',
          'Fresh ginger and garlic',
          'Cilantro for garnish',
        ],
        instructions: [
          'Sauté onion, ginger, and garlic until fragrant.',
          'Add curry powder and cook for 1 minute.',
          'Add vegetables and coconut milk.',
          'Simmer until vegetables are tender.',
          'Garnish with fresh cilantro.',
        ],
        category: 'Main Course',
        isVegetarian: true,
        isGlutenFree: true,
        containsEgg: false,
        region: 'India',
        prepTime: '20 minutes',
        cookTime: '30 minutes',
        servings: 6,
        difficulty: 'Medium',
        calories: 280,
        protein: 6,
        carbs: 45,
        fat: 12,
        notes: 'Serve with rice or naan bread',
      },
      {
        title: 'Classic Margherita Pizza',
        description:
          'Traditional Italian pizza with tomatoes, fresh mozzarella, and basil.',
        ingredients: [
          '1 pizza dough',
          '1 cup tomato sauce',
          '8 oz fresh mozzarella',
          'Fresh basil leaves',
          'Extra virgin olive oil',
          'Salt and pepper',
        ],
        instructions: [
          'Preheat oven to 450°F with pizza stone.',
          'Roll out dough and spread sauce.',
          'Top with torn mozzarella.',
          'Bake until crust is golden.',
          'Add fresh basil and olive oil.',
        ],
        category: 'Main Course',
        isVegetarian: true,
        isGlutenFree: false,
        containsEgg: false,
        region: 'Italy',
        prepTime: '20 minutes',
        cookTime: '15 minutes',
        servings: 4,
        difficulty: 'Medium',
        calories: 300,
        protein: 12,
        carbs: 35,
        fat: 15,
        notes: 'Use high-quality ingredients for best results',
      },
      {
        title: 'Mushroom Risotto',
        description:
          'Creamy Italian rice dish with mixed mushrooms and parmesan.',
        ingredients: [
          '2 cups Arborio rice',
          '500g mixed mushrooms',
          '1 onion, finely chopped',
          '4 cloves garlic, minced',
          '1 cup white wine',
          '6 cups vegetable stock',
          '1 cup parmesan cheese',
          'Fresh thyme',
          'Salt and pepper',
        ],
        instructions: [
          'Sauté onions and garlic until soft.',
          'Add mushrooms and cook until golden.',
          'Add rice and toast for 2 minutes.',
          'Add wine and simmer until absorbed.',
          'Gradually add hot stock, stirring until absorbed.',
          'Finish with parmesan and thyme.',
        ],
        category: 'Main Course',
        isVegetarian: true,
        isGlutenFree: true,
        containsEgg: false,
        region: 'Italy',
        prepTime: '15 minutes',
        cookTime: '30 minutes',
        servings: 4,
        difficulty: 'Medium',
        calories: 380,
        protein: 12,
        carbs: 58,
        fat: 9,
        notes: 'Keep stock hot while cooking for best results',
      },
      {
        title: 'Thai Green Curry',
        description: 'Aromatic coconut curry with vegetables and Thai basil.',
        ingredients: [
          '400ml coconut milk',
          '3 tbsp green curry paste',
          'Mixed vegetables',
          'Thai basil leaves',
          'Fish sauce',
          'Palm sugar',
          'Lime juice',
        ],
        instructions: [
          'Heat coconut milk in a pan.',
          'Add curry paste and simmer.',
          'Add vegetables and cook until tender.',
          'Season with fish sauce, palm sugar, and lime.',
          'Garnish with Thai basil.',
        ],
        category: 'Main Course',
        isVegetarian: true,
        isGlutenFree: true,
        containsEgg: false,
        region: 'Thailand',
        prepTime: '15 minutes',
        cookTime: '20 minutes',
        servings: 4,
        difficulty: 'Medium',
        calories: 320,
        protein: 8,
        carbs: 18,
        fat: 24,
        notes: 'Adjust curry paste amount for desired spiciness',
      },
      {
        title: 'Greek Yogurt Parfait',
        description:
          'Layered breakfast parfait with granola and fresh berries.',
        ingredients: [
          '2 cups Greek yogurt',
          '1 cup granola',
          'Mixed berries',
          'Honey',
          'Almonds, chopped',
        ],
        instructions: [
          'Layer Greek yogurt in a glass.',
          'Top with granola, fresh berries, and a drizzle of honey.',
          'Sprinkle with almonds and serve immediately.',
        ],
        category: 'Breakfast',
        isVegetarian: true,
        isGlutenFree: false,
        containsEgg: false,
        region: 'Greece',
        prepTime: '10 minutes',
        cookTime: '0 minutes',
        servings: 2,
        difficulty: 'Easy',
        calories: 280,
        protein: 14,
        carbs: 36,
        fat: 10,
        notes: 'Can be made ahead and stored in the fridge for up to 24 hours',
      },
      {
        title: 'Lentil Soup',
        description:
          'A hearty, comforting soup made with lentils and vegetables.',
        ingredients: [
          '2 cups dried lentils',
          '1 onion, chopped',
          '2 carrots, chopped',
          '2 celery stalks, chopped',
          '4 cloves garlic, minced',
          '1 can diced tomatoes',
          '6 cups vegetable broth',
          'Salt and pepper',
        ],
        instructions: [
          'Sauté onions, garlic, carrots, and celery in olive oil.',
          'Add lentils, tomatoes, and broth.',
          'Simmer for 40-45 minutes or until lentils are tender.',
          'Season with salt and pepper.',
        ],
        category: 'Soup',
        isVegetarian: true,
        isGlutenFree: true,
        containsEgg: false,
        region: 'Middle East',
        prepTime: '10 minutes',
        cookTime: '45 minutes',
        servings: 6,
        difficulty: 'Medium',
        calories: 210,
        protein: 15,
        carbs: 35,
        fat: 3,
        notes: 'Great for freezing in portions for later use',
      },
    ];

    // Clear existing recipes
    await recipeRepository.clear();

    // Insert new recipes
    for (const recipe of recipes) {
      await recipeRepository.save(recipe);
    }

    console.log('Database seeded successfully!');
  } catch (error) {
    console.error('Error seeding database:', error);
  } finally {
    await AppDataSource.destroy();
  }
};

// eslint-disable-next-line @typescript-eslint/no-floating-promises
seedDatabase();
