import { AppDataSource } from '../data-source';
import { Recipe } from '../recipes/recipe.entity';

const recipes = [
  {
    title: 'Classic Margherita Pizza',
    description:
      'Traditional Italian pizza with tomatoes, fresh mozzarella, and basil.',
    ingredients: [
      '1 pizza dough',
      '1 cup tomato sauce',
      '8 oz fresh mozzarella',
      'Fresh basil leaves',
      'Extra virgin olive oil',
      'Salt and pepper',
    ],
    instructions: [
      'Preheat oven to 450°F with pizza stone.',
      'Roll out dough and spread sauce.',
      'Top with torn mozzarella.',
      'Bake until crust is golden.',
      'Add fresh basil and olive oil.',
    ],
    category: 'Main Course',
    isVegetarian: true,
    isGlutenFree: false,
    containsEgg: false,
    region: 'Italy',
    prepTime: '20 minutes',
    cookTime: '15 minutes',
    servings: 4,
    difficulty: 'Medium',
    calories: 300,
    protein: 12,
    carbs: 35,
    fat: 15,
    notes: 'Use high-quality ingredients for best results',
  },
  {
    title: 'Thai Green Curry',
    description: 'Aromatic coconut curry with vegetables and Thai basil.',
    ingredients: [
      '400ml coconut milk',
      '3 tbsp green curry paste',
      'Mixed vegetables',
      'Thai basil leaves',
      'Fish sauce',
      'Palm sugar',
      'Lime juice',
    ],
    instructions: [
      'Heat coconut milk in a pan.',
      'Add curry paste and simmer.',
      'Add vegetables and cook until tender.',
      'Season with fish sauce, palm sugar, and lime.',
      'Garnish with Thai basil.',
    ],
    category: 'Main Course',
    isVegetarian: true,
    isGlutenFree: true,
    containsEgg: false,
    region: 'Thailand',
    prepTime: '15 minutes',
    cookTime: '20 minutes',
    servings: 4,
    difficulty: 'Medium',
    calories: 320,
    protein: 8,
    carbs: 18,
    fat: 24,
    notes: 'Adjust curry paste amount for desired spiciness',
  },
  {
    title: 'Mediterranean Quinoa Bowl',
    description: 'Healthy and protein-rich bowl with Mediterranean flavors.',
    ingredients: [
      '1 cup quinoa',
      'Cherry tomatoes',
      'Cucumber',
      'Kalamata olives',
      'Feta cheese',
      'Fresh herbs',
      'Lemon vinaigrette',
    ],
    instructions: [
      'Cook quinoa according to package instructions.',
      'Chop vegetables and herbs.',
      'Combine quinoa with vegetables.',
      'Top with feta and olives.',
      'Drizzle with vinaigrette.',
    ],
    category: 'Main Course',
    isVegetarian: true,
    isGlutenFree: true,
    containsEgg: false,
    region: 'Mediterranean',
    prepTime: '15 minutes',
    cookTime: '20 minutes',
    servings: 2,
    difficulty: 'Easy',
    calories: 450,
    protein: 15,
    carbs: 55,
    fat: 20,
    notes: 'Can be served hot or cold',
  },
  {
    title: 'Japanese Miso Ramen',
    description: 'Comforting ramen with miso broth and traditional toppings.',
    ingredients: [
      'Ramen noodles',
      'Miso paste',
      'Vegetable broth',
      'Soft-boiled egg',
      'Nori',
      'Green onions',
      'Corn kernels',
    ],
    instructions: [
      'Prepare miso broth.',
      'Cook ramen noodles.',
      'Add toppings to bowl.',
      'Pour hot broth over noodles.',
      'Garnish with nori and green onions.',
    ],
    category: 'Main Course',
    isVegetarian: false,
    isGlutenFree: false,
    containsEgg: true,
    region: 'Japan',
    prepTime: '20 minutes',
    cookTime: '15 minutes',
    servings: 2,
    difficulty: 'Medium',
    calories: 550,
    protein: 20,
    carbs: 65,
    fat: 25,
    notes: 'Use fresh noodles for best texture',
  },
  {
    title: 'Greek Yogurt Breakfast Bowl',
    description: 'Protein-rich breakfast bowl with fresh fruits and granola.',
    ingredients: [
      'Greek yogurt',
      'Mixed berries',
      'Granola',
      'Honey',
      'Chia seeds',
      'Almonds',
    ],
    instructions: [
      'Spoon Greek yogurt into bowl.',
      'Top with fresh berries.',
      'Add granola and chia seeds.',
      'Drizzle with honey.',
      'Sprinkle with chopped almonds.',
    ],
    category: 'Breakfast',
    isVegetarian: true,
    isGlutenFree: true,
    containsEgg: false,
    region: 'Greece',
    prepTime: '10 minutes',
    cookTime: '0 minutes',
    servings: 1,
    difficulty: 'Easy',
    calories: 350,
    protein: 20,
    carbs: 45,
    fat: 12,
    notes: 'Best served immediately',
  },
  {
    title: 'Mexican Street Tacos',
    description:
      'Authentic street-style tacos with marinated meat and fresh toppings.',
    ingredients: [
      'Corn tortillas',
      'Marinated meat',
      'Onions',
      'Cilantro',
      'Lime wedges',
      'Salsa verde',
    ],
    instructions: [
      'Warm tortillas.',
      'Cook marinated meat.',
      'Chop onions and cilantro.',
      'Assemble tacos.',
      'Serve with lime and salsa.',
    ],
    category: 'Main Course',
    isVegetarian: false,
    isGlutenFree: true,
    containsEgg: false,
    region: 'Mexico',
    prepTime: '20 minutes',
    cookTime: '15 minutes',
    servings: 4,
    difficulty: 'Easy',
    calories: 380,
    protein: 25,
    carbs: 30,
    fat: 18,
    notes: 'Double-wrap tortillas for better handling',
  },
  {
    title: 'Mediterranean Grilled Salmon',
    description: 'Healthy salmon with Mediterranean herbs and vegetables.',
    ingredients: [
      'Salmon fillets',
      'Olive oil',
      'Fresh herbs',
      'Lemon',
      'Cherry tomatoes',
      'Cucumber',
      'Kalamata olives',
    ],
    instructions: [
      'Season salmon with herbs.',
      'Grill until cooked through.',
      'Prepare Mediterranean salad.',
      'Plate with vegetables.',
      'Drizzle with olive oil.',
    ],
    category: 'Main Course',
    isVegetarian: false,
    isGlutenFree: true,
    containsEgg: false,
    region: 'Mediterranean',
    prepTime: '15 minutes',
    cookTime: '15 minutes',
    servings: 2,
    difficulty: 'Medium',
    calories: 450,
    protein: 35,
    carbs: 8,
    fat: 30,
    notes: 'Use fresh herbs for best flavor',
  },
  {
    title: 'Vegetable Stir-Fry',
    description: 'Quick and healthy Asian-style vegetable stir-fry.',
    ingredients: [
      'Mixed vegetables',
      'Soy sauce',
      'Ginger',
      'Garlic',
      'Sesame oil',
      'Rice',
    ],
    instructions: [
      'Prepare vegetables.',
      'Heat wok or pan.',
      'Stir-fry vegetables.',
      'Add sauce and seasonings.',
      'Serve with rice.',
    ],
    category: 'Main Course',
    isVegetarian: true,
    isGlutenFree: true,
    containsEgg: false,
    region: 'Asia',
    prepTime: '15 minutes',
    cookTime: '10 minutes',
    servings: 2,
    difficulty: 'Easy',
    calories: 300,
    protein: 8,
    carbs: 45,
    fat: 12,
    notes: 'Keep vegetables crisp',
  },
  {
    title: 'Classic Caesar Salad',
    description: 'Traditional Caesar salad with homemade dressing.',
    ingredients: [
      'Romaine lettuce',
      'Parmesan cheese',
      'Croutons',
      'Caesar dressing',
      'Black pepper',
      'Anchovies (optional)',
    ],
    instructions: [
      'Wash and chop lettuce.',
      'Make Caesar dressing.',
      'Combine ingredients.',
      'Toss with dressing.',
      'Top with parmesan.',
    ],
    category: 'Salad',
    isVegetarian: false,
    isGlutenFree: false,
    containsEgg: true,
    region: 'Italy',
    prepTime: '15 minutes',
    cookTime: '0 minutes',
    servings: 4,
    difficulty: 'Easy',
    calories: 250,
    protein: 8,
    carbs: 15,
    fat: 20,
    notes: 'Traditional dressing contains raw egg',
  },
  {
    title: 'Indian Butter Chicken',
    description: 'Rich and creamy Indian curry with tender chicken.',
    ingredients: [
      'Chicken breast',
      'Butter',
      'Heavy cream',
      'Tomato sauce',
      'Indian spices',
      'Rice',
      'Naan bread',
    ],
    instructions: [
      'Marinate chicken.',
      'Cook chicken until golden.',
      'Prepare sauce.',
      'Combine and simmer.',
      'Serve with rice and naan.',
    ],
    category: 'Main Course',
    isVegetarian: false,
    isGlutenFree: true,
    containsEgg: false,
    region: 'India',
    prepTime: '20 minutes',
    cookTime: '30 minutes',
    servings: 4,
    difficulty: 'Medium',
    calories: 550,
    protein: 35,
    carbs: 45,
    fat: 25,
    notes: 'Marinate chicken overnight for best flavor',
  },
  {
    title: 'Fresh Pasta Primavera',
    description: 'Light and fresh pasta with spring vegetables.',
    ingredients: [
      'Fresh pasta',
      'Mixed spring vegetables',
      'Olive oil',
      'Garlic',
      'Fresh herbs',
      'Parmesan cheese',
    ],
    instructions: [
      'Cook pasta until al dente.',
      'Sauté vegetables.',
      'Combine pasta and vegetables.',
      'Add herbs and cheese.',
      'Drizzle with olive oil.',
    ],
    category: 'Main Course',
    isVegetarian: true,
    isGlutenFree: false,
    containsEgg: true,
    region: 'Italy',
    prepTime: '20 minutes',
    cookTime: '15 minutes',
    servings: 4,
    difficulty: 'Medium',
    calories: 450,
    protein: 15,
    carbs: 55,
    fat: 18,
    notes: 'Use seasonal vegetables for best results',
  },
];

async function seedRecipes() {
  try {
    await AppDataSource.initialize();
    console.log('Data Source has been initialized!');

    const recipeRepository = AppDataSource.getRepository(Recipe);

    for (const recipe of recipes) {
      const newRecipe = recipeRepository.create(recipe);
      await recipeRepository.save(newRecipe);
    }

    console.log('Database seeded successfully!');
  } catch (error) {
    console.error('Error seeding database:', error);
  } finally {
    await AppDataSource.destroy();
  }
}

// eslint-disable-next-line @typescript-eslint/no-floating-promises
seedRecipes();
