import { AppDataSource } from '../data-source';
import { Recipe } from '../recipes/recipe.entity';

async function seedRecipes() {
  await AppDataSource.initialize();
  const recipeRepo = AppDataSource.getRepository(Recipe);

  const recipes: Partial<Recipe>[] = [
    {
      title: 'Spicy Paneer Tikka Wrap',
      description: 'Spicy marinated paneer wrapped in soft roti with veggies.',
      ingredients: ['Paneer', 'Yogurt', 'Spices', 'Capsicum', 'Onion', 'Roti'],
      instructions: [
        'Marinate paneer',
        'Grill paneer',
        'Assemble in roti',
        'Serve hot',
      ],
      category: 'Lunch',
      isVegetarian: true,
      isGlutenFree: false,
      containsEgg: false,
      region: 'India',
      prepTime: '15 mins',
      cookTime: '15 mins',
      servings: 2,
      difficulty: 'Medium',
      calories: 400,
      protein: 20,
      carbs: 35,
      fat: 22,
      notes: 'Serve with mint chutney',
      authorId: 1,
      authorName: 'Shravani',
    },
    {
      title: 'Zucchini Noodles in Garlic Sauce',
      description: 'Low-carb spiralized zucchini tossed in garlicky goodness.',
      ingredients: ['Zucchini', 'Garlic', 'Olive oil', 'Chili flakes'],
      instructions: [
        'Spiralize zucchini',
        'Saute garlic in oil',
        'Toss noodles',
        'Serve warm',
      ],
      category: 'Dinner',
      isVegetarian: true,
      isGlutenFree: true,
      containsEgg: false,
      region: 'Italy',
      prepTime: '10 mins',
      cookTime: '10 mins',
      servings: 1,
      difficulty: 'Easy',
      calories: 200,
      protein: 5,
      carbs: 10,
      fat: 12,
      notes: '',
      authorId: 1,
      authorName: 'Shravani',
    },
    {
      title: 'Masala Oats Bowl',
      description: 'Savory oats cooked with Indian spices and veggies.',
      ingredients: ['Oats', 'Vegetables', 'Spices', 'Water'],
      instructions: [
        'Heat pan',
        'Add veggies and spices',
        'Mix oats & cook',
        'Serve hot',
      ],
      category: 'Breakfast',
      isVegetarian: true,
      isGlutenFree: true,
      containsEgg: false,
      region: 'India',
      prepTime: '5 mins',
      cookTime: '10 mins',
      servings: 1,
      difficulty: 'Easy',
      calories: 250,
      protein: 7,
      carbs: 30,
      fat: 8,
      notes: 'Add ghee for flavor',
      authorId: 1,
      authorName: 'Shravani',
    },
    {
      title: 'Creamy Avocado Toast',
      description: 'Toasted bread topped with creamy avocado mash.',
      ingredients: ['Bread', 'Avocado', 'Lemon', 'Chili flakes'],
      instructions: [
        'Toast bread',
        'Mash avocado',
        'Spread and season',
        'Serve',
      ],
      category: 'Breakfast',
      isVegetarian: true,
      isGlutenFree: false,
      containsEgg: false,
      region: 'USA',
      prepTime: '5 mins',
      cookTime: '2 mins',
      servings: 1,
      difficulty: 'Easy',
      calories: 300,
      protein: 6,
      carbs: 28,
      fat: 18,
      notes: 'Top with poached egg optionally',
      authorId: 1,
      authorName: 'Shravani',
    },
    {
      title: 'Vegetable Quinoa Pilaf',
      description: 'Nutritious quinoa with mixed veggies and light spices.',
      ingredients: ['Quinoa', 'Mixed vegetables', 'Spices', 'Salt'],
      instructions: [
        'Cook quinoa',
        'Sauté veggies',
        'Mix & simmer',
        'Serve warm',
      ],
      category: 'Lunch',
      isVegetarian: true,
      isGlutenFree: true,
      containsEgg: false,
      region: 'Middle East',
      prepTime: '10 mins',
      cookTime: '20 mins',
      servings: 2,
      difficulty: 'Medium',
      calories: 350,
      protein: 12,
      carbs: 40,
      fat: 10,
      notes: '',
      authorId: 1,
      authorName: 'Shravani',
    },
    {
      title: 'Lemon Herb Grilled Chicken',
      description: 'Juicy chicken grilled with lemon and herbs.',
      ingredients: ['Chicken breast', 'Lemon juice', 'Herbs', 'Garlic'],
      instructions: [
        'Marinate chicken',
        'Grill until cooked',
        'Serve with salad',
      ],
      category: 'Dinner',
      isVegetarian: false,
      isGlutenFree: true,
      containsEgg: false,
      region: 'Greece',
      prepTime: '20 mins',
      cookTime: '15 mins',
      servings: 2,
      difficulty: 'Easy',
      calories: 400,
      protein: 35,
      carbs: 5,
      fat: 22,
      notes: '',
      authorId: 1,
      authorName: 'Shravani',
    },
    {
      title: 'Egg Mayo Sandwich',
      description: 'Classic sandwich with egg and mayo filling.',
      ingredients: ['Bread', 'Boiled eggs', 'Mayonnaise', 'Salt', 'Pepper'],
      instructions: [
        'Boil eggs',
        'Mash with mayo',
        'Spread on bread',
        'Toast or serve',
      ],
      category: 'Snack',
      isVegetarian: false,
      isGlutenFree: false,
      containsEgg: true,
      region: 'UK',
      prepTime: '10 mins',
      cookTime: '0 mins',
      servings: 1,
      difficulty: 'Easy',
      calories: 350,
      protein: 15,
      carbs: 30,
      fat: 20,
      notes: '',
      authorId: 1,
      authorName: 'Shravani',
    },
    {
      title: 'Spicy Korean Chicken Rice Bowl',
      description: 'Flavorful Korean-style chicken served over steamed rice.',
      ingredients: ['Chicken', 'Gochujang', 'Rice', 'Veggies'],
      instructions: [
        'Cook chicken in gochujang',
        'Steam rice',
        'Assemble bowl',
        'Serve hot',
      ],
      category: 'Dinner',
      isVegetarian: false,
      isGlutenFree: false,
      containsEgg: false,
      region: 'Korea',
      prepTime: '15 mins',
      cookTime: '20 mins',
      servings: 2,
      difficulty: 'Medium',
      calories: 500,
      protein: 30,
      carbs: 45,
      fat: 22,
      notes: '',
      authorId: 1,
      authorName: 'Shravani',
    },
    {
      title: 'Butter Garlic Prawns',
      description: 'Succulent prawns cooked in butter garlic sauce.',
      ingredients: ['Prawns', 'Butter', 'Garlic', 'Parsley'],
      instructions: [
        'Clean prawns',
        'Cook in butter & garlic',
        'Garnish and serve',
      ],
      category: 'Dinner',
      isVegetarian: false,
      isGlutenFree: true,
      containsEgg: false,
      region: 'Coastal India',
      prepTime: '10 mins',
      cookTime: '10 mins',
      servings: 2,
      difficulty: 'Easy',
      calories: 300,
      protein: 25,
      carbs: 2,
      fat: 18,
      notes: '',
      authorId: 1,
      authorName: 'Shravani',
    },
    {
      title: 'Classic Egg Fried Rice',
      description: 'Fried rice with eggs, veggies and soy sauce.',
      ingredients: ['Rice', 'Eggs', 'Veggies', 'Soy sauce'],
      instructions: [
        'Scramble eggs',
        'Add rice & veggies',
        'Toss with soy sauce',
        'Serve',
      ],
      category: 'Lunch',
      isVegetarian: false,
      isGlutenFree: false,
      containsEgg: true,
      region: 'China',
      prepTime: '10 mins',
      cookTime: '10 mins',
      servings: 2,
      difficulty: 'Easy',
      calories: 400,
      protein: 15,
      carbs: 40,
      fat: 12,
      notes: '',
      authorId: 1,
      authorName: 'Shravani',
    },
  ];

  await recipeRepo.save(recipes);
  console.log('🌱 Successfully seeded 10 recipes!');
  process.exit(0);
}

seedRecipes().catch((err) => {
  console.error('❌ Error seeding recipes:', err);
  process.exit(1);
});
